spring.datasource.url=jdbc:postgresql://localhost:5433/blogging
spring.datasource.username=postgres
spring.datasource.password=****
server.port=8080

spring.jpa.properties.hibernate.default_schema=blogging_app